#!/usr/bin/env sh

case `uname` in
    (*CYGWIN*|*MINGW*|*MSYS*)
        # fallback for Windows users.
        . "$(dirname -- "$0")/_/husky.sh"
        echo "$1"
        npx commitlint --edit 
    exit 1;;
esac

