#!/usr/bin/env sh
# // https://github.com/commitizen/cz-cli/issues/627

case `uname` in
    (*CYGWIN*|*MINGW*|*MSYS*)
        exit 0
    exit 1;;
esac
. "$(dirname "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"
exec < /dev/tty && node_modules/.bin/cz --hook || true
