#!/usr/bin/env sh
# // https://github.com/commitizen/cz-cli/issues/627
. "$(dirname -- "$0")/_/husky.sh"
case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        . "$(dirname -- "$0")/common.sh"
        exit 0
    ;;
esac
exec < /dev/tty && node_modules/.bin/cz --hook || true
