#!/usr/bin/env sh
# // https://github.com/commitizen/cz-cli/issues/627

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        exit 0
    exit 1;;
esac
. "$(dirname "$0")/_/husky.sh"
. "$(dirname -- "$0")/common.sh"
exec < /dev/tty && node_modules/.bin/cz --hook || true

#. "$(dirname -- "$0")/_/husky.sh"
#. "$(dirname -- "$0")/common.sh"


# # `CI` env variable should exists in most CI/CD environments
# if [[ -z "${CI}" ]]; then
#   # only run in non CI environments - e.g: dev machine
#   exec < /dev/tty && node_modules/.bin/cz --hook || true
# fi

# if [ -t 1 ]; then
#   exec < /dev/tty && node_modules/.bin/cz --hook || true
# fi
#   exec < /dev/tty && node_modules/.bin/cz --hook || true
# else
#   node_modules/.bin/cz --hook || true
# fi
# if [ -t 1 ]; then
#   exec < /dev/tty
# fi
# node_modules/.bin/cz --hook

#true || node_modules/.bin/cz --hook